import { UiColumnMappings } from "../../tableDefinitions";

export const sessionCols: UiColumnMappings = [
  // we do not access the scores when building session column mappings; fall back to trace timestamps.

  {
    uiTableName: "⭐️",
    uiTableId: "bookmarked",
    tableName: "traces",
    select: "bookmarked",
  },
  {
    uiTableName: "Created At",
    uiTableId: "createdAt",
    tableName: "traces",
    select: "min_timestamp",
  },
  {
    uiTableName: "User IDs",
    uiTableId: "userIds",
    tableName: "traces",
    select: "user_ids",
  },
  {
    uiTableName: "Environment",
    uiTableId: "environment",
    tableName: "traces",
    select: "environment",
  },
  {
    uiTableName: "Session Duration",
    uiTableId: "sessionDuration",
    tableName: "traces",
    select: "duration",
    // If we use the default of Decimal64(12), we cannot filter for more than ~40min due to an overflow
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Count Traces",
    uiTableId: "countTraces",
    tableName: "traces",
    select: "trace_count",
  },
  {
    uiTableName: "Session Input Cost",
    uiTableId: "inputCost",
    tableName: "traces",
    select: "session_input_cost",
  },
  {
    uiTableName: "Session Output Cost",
    uiTableId: "outputCost",
    tableName: "traces",
    select: "session_output_cost",
  },
  {
    uiTableName: "Session Total Cost",
    uiTableId: "totalCost",
    tableName: "traces",
    select: "session_total_cost",
  },
  {
    uiTableName: "Input Tokens",
    uiTableId: "inputTokens",
    tableName: "traces",
    select: "session_input_usage",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Output Tokens",
    uiTableId: "outputTokens",
    tableName: "traces",
    select: "session_output_usage",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Total Tokens",
    uiTableId: "totalTokens",
    tableName: "traces",
    select: "session_total_usage",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Usage",
    uiTableId: "totalTokens",
    tableName: "traces",
    select: "session_total_usage",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Session Total Usage",
    uiTableId: "usage",
    tableName: "traces",
    select: "session_total_usage",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Session Duration (s)",
    uiTableId: "sessionDuration",
    tableName: "traces",
    select: "duration",
    // If we use the default of Decimal64(12), we cannot filter for more than ~40min due to an overflow
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Traces Count",
    uiTableId: "tracesCount",
    tableName: "traces",
    select: "trace_count",
  },
  {
    uiTableName: "Input Cost ($)",
    uiTableId: "inputCost",
    tableName: "traces",
    select: "session_input_cost",
  },
  {
    uiTableName: "Output Cost ($)",
    uiTableId: "outputCost",
    tableName: "traces",
    select: "session_output_cost",
  },
  {
    uiTableName: "Total Cost ($)",
    uiTableId: "totalCost",
    tableName: "traces",
    select: "session_total_cost",
  },
  {
    uiTableName: "Trace Tags",
    uiTableId: "traceTags",
    tableName: "traces",
    select: "trace_tags",
  },
  {
    uiTableName: "ID",
    uiTableId: "id",
    tableName: "traces",
    select: "session_id",
  },
  {
    uiTableName: "Scores (numeric)",
    uiTableId: "scores_avg",
    tableName: "scores",
    select: "scores_avg",
  },
  {
    uiTableName: "Scores (categorical)",
    uiTableId: "score_categories",
    tableName: "scores",
    select: "score_categories",
  },
];

// Doris version of sessionCols with database-specific function adaptations
export const sessionColsForDoris: UiColumnMappings = [
  {
    uiTableName: "⭐️",
    uiTableId: "bookmarked",
    tableName: "traces",
    select: "bookmarked",
  },
  {
    uiTableName: "Created At",
    uiTableId: "createdAt",
    tableName: "traces",
    select: "min_timestamp",
  },
  {
    uiTableName: "User IDs",
    uiTableId: "userIds",
    tableName: "traces",
    select: "user_ids",
  },
  {
    uiTableName: "Environment",
    uiTableId: "environment",
    tableName: "traces",
    select: "environment",
  },
  {
    uiTableName: "Session Duration",
    uiTableId: "sessionDuration",
    tableName: "traces",
    select: "duration",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Count Traces",
    uiTableId: "countTraces",
    tableName: "traces",
    select: "trace_count",
  },
  {
    uiTableName: "Session Input Cost",
    uiTableId: "inputCost",
    tableName: "traces",
    select: "session_input_cost",
  },
  {
    uiTableName: "Session Output Cost",
    uiTableId: "outputCost",
    tableName: "traces",
    select: "session_output_cost",
  },
  {
    uiTableName: "Session Total Cost",
    uiTableId: "totalCost",
    tableName: "traces",
    select: "session_total_cost",
  },
  {
    uiTableName: "Input Tokens",
    uiTableId: "inputTokens",
    tableName: "traces",
    select: "session_input_usage",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Output Tokens",
    uiTableId: "outputTokens",
    tableName: "traces",
    select: "session_output_usage",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Total Tokens",
    uiTableId: "totalTokens",
    tableName: "traces",
    select: "session_total_usage",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Usage",
    uiTableId: "totalTokens",
    tableName: "traces",
    select: "session_total_usage",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Session Total Usage",
    uiTableId: "usage",
    tableName: "traces",
    select: "session_total_usage",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Session Duration (s)",
    uiTableId: "sessionDuration",
    tableName: "traces",
    select: "duration",
    typeOverwrite: "Decimal64(3)",
  },
  {
    uiTableName: "Traces Count",
    uiTableId: "tracesCount",
    tableName: "traces",
    select: "trace_count",
  },
  {
    uiTableName: "Input Cost ($)",
    uiTableId: "inputCost",
    tableName: "traces",
    select: "session_input_cost",
  },
  {
    uiTableName: "Output Cost ($)",
    uiTableId: "outputCost",
    tableName: "traces",
    select: "session_output_cost",
  },
  {
    uiTableName: "Total Cost ($)",
    uiTableId: "totalCost",
    tableName: "traces",
    select: "session_total_cost",
  },
  {
    uiTableName: "Trace Tags",
    uiTableId: "traceTags",
    tableName: "traces",
    select: "trace_tags",
  },
  {
    uiTableName: "ID",
    uiTableId: "id",
    tableName: "traces",
    select: "session_id",
  },
  {
    uiTableName: "Scores (numeric)",
    uiTableId: "scores_avg",
    tableName: "scores",
    select: "scores_avg",
  },
  {
    uiTableName: "Scores (categorical)",
    uiTableId: "score_categories",
    tableName: "scores",
    select: "score_categories",
  },
];
